Repository priyajag72/battleship, pull requests merged in 2020-07, with the labels that each got.

#2 Ship feature
  lib/ship.rb
  test/ship_test.rb
Labels: Ready To Merge?

#4 Cell feature
  lib/cell.rb
  lib/ship.rb
  test/cell_test.rb
Labels: Peer Tested, Reviewer - Merged to Dev Branch!

#5 Shift out tests to reflect our Hash and have tests pass.
  test/board_test.rb
Labels: Peer Tested, Reviewer - merged from update to feature branch, Writer - Ready to Merge

#6 Refactor generate_cells method
  lib/board.rb
Labels: Refactor

#3 Board feature - generate cells method functioning
  lib/board.rb
  test/board_test.rb
Labels: Bug Fixed, Reviewer - Merged to Dev Branch!, Writer - Ready to Merge

#9 Created valid_coordinate? method to test that the coordinate can or can't exist in the cell.
  lib/board.rb
  test/board_test.rb
Labels: Peer Tested, Reviewer - Merge to Board Feature Branch, Writer - Please Review

#11 Valid placement method created and thoroughly tested :)
  lib/board.rb
  test/board_test.rb
Labels: Screen-Share Peer Tested, Writer - Please Review

#10 Placing ships feature
  lib/board.rb
  test/board_test.rb
Labels: Peer Tested, Reviewer - Merge to Board Feature Branch, Writer - Please Review

#12 Board Feature
  lib/board.rb
  test/board_test.rb
Labels: Complete Feature Pull into Dev Branch, Writer - Ready to Merge

#14 Accessible Render Feature to continue to play with code.
  lib/board.rb
  lib/cell.rb
  test/board_test.rb
  test/ship_test.rb
Labels: playground pull requests

#13 Render feature & Ship_over_lay method bug fix
  lib/board.rb
  lib/cell.rb
  test/board_test.rb
  test/ship_test.rb
Labels: Bug Fixed, Peer Tested, Refactor, Reviewer - Merged to Dev Branch!, Screen-Share Peer Tested, Writer - Ready to Merge

#15 Working through player class that game class will access.
  lib/player.rb
  test/player_test.rb
Labels: Please Help! <3, Screen-Share Peer Tested, Writer - Please Review

#16 Player feature auto
  lib/board.rb
  lib/player.rb
  test/board_test.rb
  test/player_test.rb
Labels: Peer Tested, Please Help! <3, Refactor, Reviewer - merged from update to feature branch, Writer - Please Review, Writer - Ready to Merge

#17 Turn Feature CANCELLED :)
  lib/board.rb
  lib/cell.rb
  lib/game.rb
  lib/player.rb
  lib/ship.rb
  lib/turn.rb
  test/board_test.rb
  test/cell_test.rb
  test/game_test.rb
  test/player_test.rb
  test/ship_test.rb
  test/turn_test.rb
Labels: AHA Moment - This belongs elsewhere

#18 Revert 17 turn feature
  lib/board.rb
  lib/cell.rb
  lib/game.rb
  lib/player.rb
  lib/ship.rb
  test/board_test.rb
  test/cell_test.rb
  test/game_test.rb
  test/player_test.rb
  test/ship_test.rb
Labels: Revert! Revert!

#20 Working on Game Class
  lib/game.rb
  test/game_test.rb
Labels: Please Help! <3, Screen-Share Peer Tested, Writer - Please Review

#21 Updates testing for Fire method && Working on Fire Coordinate method.
  lib/game.rb
  lib/player.rb
  test/game_test.rb
Labels: Refactor Updated, Writer - Ready to Merge

#23 Fire and start and runner
  lib/battleship.rb
  lib/board.rb
  lib/cell.rb
  lib/game.rb
  lib/player.rb
  lib/ship.rb
  runner.rb
  test/board_test.rb
  test/game_test.rb
  test/player_test.rb
Labels: Found Bug, Peer Tested, Please Help! <3, Refactor Updated, Reviewer - Merged to Dev Branch!, Writer - Please Review, Writer - Ready to Merge

#24 Terminal title
  lib/game.rb
  test/game_test.rb
Labels: Writer - Ready to Merge

#25 Looking for bugs feature
  lib/game.rb
  lib/player.rb
  test/game_test.rb
Labels: Peer Tested, Refactor, Reviewer - Merged to Dev Branch!, Reviewer - merged from update to feature branch, Writer - Ready to Merge

#26 Development2
  lib/battleship.rb
  lib/board.rb
  lib/cell.rb
  lib/game.rb
  lib/player.rb
  lib/ship.rb
  runner.rb
  test/board_test.rb
  test/cell_test.rb
  test/game_test.rb
  test/player_test.rb
  test/ship_test.rb
Labels: Reviewer: Merge to Main, Screen-Share Peer Tested, Writer - Please Review
